FROM python:3.7

ARG pip_installer="https://bootstrap.pypa.io/get-pip.py"


# install sam
ENV PATH $PATH:/root/.local/bin

# install command.
RUN apt update && apt install -y less vim wget unzip curl

# install terraform.
RUN wget https://releases.hashicorp.com/terraform/0.12.5/terraform_0.12.5_linux_amd64.zip && \
    unzip ./terraform_0.12.5_linux_amd64.zip -d /usr/local/bin/

# create workspace.
COPY ./src/main.tf /root/src/
COPY ./src/providers.tf /root/src/
COPY ./src/variables.tf /root/src/
ADD  ./src /root/src/

# initialize command.
ARG ARM_SUBSCRIPTION_ID
ARG ARM_CLIENT_ID
ARG ARM_CLIENT_SECRET
ARG ARM_TENANT_ID
COPY .aws /root/.aws
COPY init.sh /root/init.sh
RUN chmod +x /root/init.sh && /root/init.sh

WORKDIR /root/src
